services:
  - type: web
    name: feriwala-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        sync: false # Will be set in Render dashboard
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 7d
      - key: JWT_REFRESH_EXPIRE
        value: 30d
      - key: SMTP_HOST
        value: smtp.zoho.in
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        sync: false # Will be set in Render dashboard
      - key: SMTP_PASS
        sync: false # Will be set in Render dashboard